// <auto-generated />
namespace S2021A6FH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class artistMedia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(artistMedia));
        
        string IMigrationMetadata.Id
        {
            get { return "202108102233102_artistMedia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
